version: '3.8'

services:
    nginx:
        image: nginx:1.21.1
        ports:
            - "80:80"
        volumes:
            - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./backend/src:/var/www/
        depends_on:
            - php

    php:
        build: ./backend/docker/php
        volumes:
            - ./backend/src:/var/www/

    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: share_db
            MYSQL_USER: share_user
            MYSQL_PASSWORD: share_pass
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./backend/docker/mysql/data:/var/lib/mysql
            - ./backend/docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=share_user
            - PMA_PASSWORD=share_pass
        depends_on:
            - mysql
        ports:
            - 8080:80
